// 50 Websites That Feel Illegal to Know 🚨
// Data source: user-provided viral list, URLs verified/mapped to official domains.
const SITES = [
  { n: 1, icon: "📚", name: "NotebookLM", url: "https://notebooklm.google.com/", desc: "Turns any document into a podcast", cat: "AI & Productivity" },
  { n: 2, icon: "🖌️", name: "Photopea", url: "https://www.photopea.com/", desc: "Free Photoshop in your browser", cat: "Design & Images" },
  { n: 3, icon: "✂️", name: "remove.bg", url: "https://www.remove.bg/", desc: "Instant photo background removal", cat: "Design & Images" },
  { n: 4, icon: "🧰", name: "TinyWow", url: "https://tinywow.com/", desc: "Every free online tool in one place", cat: "Utilities" },
  { n: 5, icon: "✈️", name: "Skiplagged", url: "https://skiplagged.com/", desc: "Find cheaper flight routes", cat: "Travel" },
  { n: 6, icon: "🛰️", name: "FlightRadar24", url: "https://www.flightradar24.com/", desc: "Track any flight live", cat: "Travel" },
  { n: 7, icon: "💥", name: "NUKEMAP", url: "https://nuclearsecrecy.com/nukemap/", desc: "Simulate blast radius maps", cat: "Research & Data" },
  { n: 8, icon: "🕵️", name: "LittleSis", url: "https://littlesis.org/", desc: "See who is connected to who", cat: "Research & Data" },
  { n: 9, icon: "🤖", name: "ThisPersonDoesNotExist", url: "https://thispersondoesnotexist.com/", desc: "AI faces that never existed", cat: "AI & Productivity" },
  { n: 10, icon: "🧽", name: "Cleanup.pictures", url: "https://cleanup.pictures/", desc: "Erase objects from any photo", cat: "Design & Images" },
  { n: 11, icon: "🔍", name: "OSINT Framework", url: "https://osintframework.com/", desc: "Every research tool in one map", cat: "Research & Data" },
  { n: 12, icon: "🔐", name: "Have I Been Pwned", url: "https://haveibeenpwned.com/", desc: "Check if your data was leaked", cat: "Privacy & Security" },
  { n: 13, icon: "📧", name: "Temp Mail", url: "https://temp-mail.org/", desc: "Disposable email in seconds", cat: "Privacy & Security" },
  { n: 14, icon: "🦠", name: "VirusTotal", url: "https://www.virustotal.com/", desc: "Scan any file or link for threats", cat: "Privacy & Security" },
  { n: 15, icon: "🕶️", name: "BrowserLeaks", url: "https://browserleaks.com/", desc: "See what websites know about you", cat: "Privacy & Security" },
  { n: 16, icon: "💻", name: "Ninite", url: "https://ninite.com/", desc: "Install all your apps at once", cat: "Utilities" },
  { n: 17, icon: "🍳", name: "JustTheRecipe", url: "https://www.justtherecipe.com/", desc: "Skip the story, get the recipe", cat: "Lifestyle" },
  { n: 18, icon: "📻", name: "Radio Garden", url: "https://radio.garden/", desc: "Listen to radio from any country", cat: "Lifestyle" },
  { n: 19, icon: "🧮", name: "Wolfram Alpha", url: "https://www.wolframalpha.com/", desc: "Solves any math problem instantly", cat: "Research & Data" },
  { n: 20, icon: "🔎", name: "DuckDuckGo", url: "https://duckduckgo.com/", desc: "Search without being tracked", cat: "Privacy & Security" },
  { n: 21, icon: "🥘", name: "Supercook", url: "https://www.supercook.com/", desc: "Recipes from what is in your fridge", cat: "Lifestyle" },
  { n: 22, icon: "💪", name: "MuscleWiki", url: "https://musclewiki.com/", desc: "Every exercise explained visually", cat: "Lifestyle" },
  { n: 23, icon: "🔄", name: "CloudConvert", url: "https://cloudconvert.com/", desc: "Convert any file format free", cat: "Utilities" },
  { n: 24, icon: "☎️", name: "GetHuman", url: "https://gethuman.com/", desc: "Skip the robot, reach a real person", cat: "Utilities" },
  { n: 25, icon: "📜", name: "ToS;DR", url: "https://tosdr.org/", desc: "Terms of service made short", cat: "Privacy & Security" },
  { n: 26, icon: "🧩", name: "OpenSourceAlternative.to", url: "https://www.opensourcealternative.to/", desc: "Free swaps for paid software", cat: "Utilities" },
  { n: 27, icon: "📝", name: "Jotform", url: "https://www.jotform.com/", desc: "Build forms without code", cat: "AI & Productivity" },
  { n: 28, icon: "🚧", name: "RemovePaywall", url: "https://www.removepaywall.com/", desc: "Read articles blocked by paywalls", cat: "Research & Data" },
  { n: 29, icon: "⚡", name: "rocket.new", url: "https://www.rocket.new/", desc: "Turn one prompt into a working app", cat: "AI & Productivity" },
  { n: 30, icon: "🗣️", name: "Forvo", url: "https://forvo.com/", desc: "Hear real people pronounce any word", cat: "Research & Data" },
  { n: 31, icon: "📊", name: "DrawCharts", url: "https://drawcharts.xyz/", desc: "Turn text into charts instantly", cat: "AI & Productivity" },
  { n: 32, icon: "🤖", name: "What AI Can Do Today", url: "https://whataicandotoday.com/", desc: "Find the right AI for any task", cat: "AI & Productivity" },
  { n: 33, icon: "📖", name: "OneLook", url: "https://www.onelook.com/", desc: "Find a word from its description", cat: "Research & Data" },
  { n: 34, icon: "🎬", name: "IHaveNoTV", url: "https://ihavenotv.com/", desc: "Watch documentaries free", cat: "Lifestyle" },
  { n: 35, icon: "🎨", name: "Mind the Graph", url: "https://mindthegraph.com/", desc: "Build scientific figures fast", cat: "Design & Images" },
  { n: 36, icon: "🔓", name: "Unpaywall", url: "https://unpaywall.org/", desc: "Legally skip journal paywalls", cat: "Research & Data" },
  { n: 37, icon: "🏢", name: "OpenCorporates", url: "https://opencorporates.com/", desc: "Look up any company on earth", cat: "Research & Data" },
  { n: 38, icon: "📄", name: "FlowCV", url: "https://flowcv.com/", desc: "Build a resume with no watermark", cat: "Utilities" },
  { n: 39, icon: "⬇️", name: "Cobalt", url: "https://cobalt.tools/", desc: "Clean video downloads no watermark", cat: "Utilities" },
  { n: 40, icon: "📷", name: "Pexels", url: "https://www.pexels.com/", desc: "Free stock photos and video", cat: "Design & Images" },
  { n: 41, icon: "🖼️", name: "Perchance", url: "https://perchance.org/", desc: "Unlimited AI images no sign up", cat: "AI & Productivity" },
  { n: 42, icon: "🎓", name: "Harvard CS50", url: "https://cs50.harvard.edu/x/", desc: "Real Harvard course completely free", cat: "Learning" },
  { n: 43, icon: "🏫", name: "MIT OpenCourseWare", url: "https://ocw.mit.edu/", desc: "Full MIT classes free", cat: "Learning" },
  { n: 44, icon: "🕰️", name: "Wayback Machine", url: "https://web.archive.org/", desc: "See any website from the past", cat: "Research & Data" },
  { n: 45, icon: "🗺️", name: "TrueSizeOf", url: "https://www.truesizeof.com/", desc: "Compare real country sizes", cat: "Research & Data" },
  { n: 46, icon: "📦", name: "SmallPDF", url: "https://smallpdf.com/", desc: "Edit and merge PDFs free", cat: "Utilities" },
  { n: 47, icon: "🎨", name: "Coolors", url: "https://coolors.co/", desc: "Generate color palettes instantly", cat: "Design & Images" },
  { n: 48, icon: "🔤", name: "Fontjoy", url: "https://fontjoy.com/", desc: "Pair fonts using AI", cat: "Design & Images" },
  { n: 49, icon: "🖌️", name: "Pixlr", url: "https://pixlr.com/", desc: "Free online photo editor", cat: "Design & Images" },
  { n: 50, icon: "🧠", name: "Elements of AI", url: "https://www.elementsofai.com/", desc: "Free intro to AI by Helsinki University", cat: "Learning" },
];
